package initcmd

// ConfigTemplate is the default config.toml content written by `ja2en init`.
const ConfigTemplate = `# ja2en config — generated by ja2en init
#
# Profile precedence (highest to lowest):
#   --prompt-file <path>   ad-hoc prompt file (overrides profile prompt)
#   --model <slug>         ad-hoc model
#   --profile <name>       pick a named profile from this file
#
# When no flags are passed, default_profile is used.

default_profile = "simple"
# OpenAI's first open-weight model. Free tier supports system prompts
# (Google's Gemma free tier does NOT, so avoid gemma-*:free here).
model = "openai/gpt-oss-120b:free"
api_base = "https://openrouter.ai/api/v1"
timeout_seconds = 30

[profiles.simple]
prompt = """
You are a Japanese-to-English translator specializing in technical content for software engineers.
Translate the input Japanese text into natural English used by native engineers.
Output ONLY the translation. No explanations, no notes, no formatting, no quotes.
"""

# To enable a custom detailed profile:
#   1. Create your prompt file at ~/.config/ja2en/prompts/detailed.md
#   2. Uncomment the section below
#
# [profiles.detailed]
# prompt_file = "~/.config/ja2en/prompts/detailed.md"
# model = "openai/gpt-oss-120b:free"   # optional override
`
